### PR TITLE
Remove default implicit configuration that sets the concurrency to 1 …

### PR DESCRIPTION
**Pull request by cjelger**
…#183

- remove implicit configuration values for memory, concurrency, and timeout

### CODE REVIEW

**Comment by cjelger** [comment]
@jthomas I'd have liked to adapt unit tests but I have been surprised there isn't any for the `compileFunction` method. Shall I add one, or did you have a reason not to have one?

**Comment by jthomas** [comment]
@cjelger Please add as many unit tests are you like :)

**Comment by cjelger** [comment]
Done in the mean time, I added one to cover the `compileFunction` method.

**Comment by cjelger** [comment]
Closes #183

**Pull request merged**
